name: ctfd
# name_app: ctfd-app
author: phoekoby

ports:
  container: 8000
  port: 80
cpu: "500m"
memory: "128Mi"

log_folder: /var/log/CTFd

namespace: default

database:
  url: mysql+pymysql://ctfd:ctfd@db-mariadb.default.svc.cluster.local/ctfd
redis: 
  url: redis://:ctfd@redis-master.default.svc.cluster.local:6379/ctfd
