apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.name}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{.Values.name}}
#   ingressClassName: ctfd
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.name}}
            port:
              number: {{.Values.ports.port}}