apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  ports:
    - port: {{.Values.ports.port}}
#   ClusterIP: None
  type: ClusterIP
  selector:
    app: {{.Values.name}}